# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionTodo < Formula
  desc "A command-line interface for managing todo items using Notion database integration"
  homepage "https://github.com/caffeines/notion-todo"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caffeines/notion-todo/releases/download/v1.0.5/notion-todo_Darwin_x86_64.tar.gz"
      sha256 "dffd7a28769f19c149d37c326012ae1dc205c3368f7b31c319e6147e028f4e8a"

      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caffeines/notion-todo/releases/download/v1.0.5/notion-todo_Darwin_arm64.tar.gz"
      sha256 "b37c493e51b61f6fcaef8014465540f4b3448da6e52a60ea42062008ac517d07"

      def install
        bin.install "todo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/caffeines/notion-todo/releases/download/v1.0.5/notion-todo_Linux_x86_64.tar.gz"
      sha256 "964b56e8c64e331b6779e7bc05e4d2e200f93d66b1871da7662734a65b56d91a"
      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/caffeines/notion-todo/releases/download/v1.0.5/notion-todo_Linux_arm64.tar.gz"
      sha256 "eb7be88dd9f2dd88146dc63370e68a63063c832c8bfaa3eec374c69a1b23e332"
      def install
        bin.install "todo"
      end
    end
  end

  test do
    system "#{bin}/todo version"
  end
end
