# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionTodo < Formula
  desc "A command-line interface for managing todo items using Notion database integration"
  homepage "https://github.com/caffeines/notion-todo"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caffeines/notion-todo/releases/download/v1.0.0/notion-todo_Darwin_x86_64.tar.gz"
      sha256 "a15cc183917b8198ff03a13451a7ca42a9514a592c08cdc581665030ac6b0bb8"

      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caffeines/notion-todo/releases/download/v1.0.0/notion-todo_Darwin_arm64.tar.gz"
      sha256 "902caf82956e0cb53dbf75ded7b773d9ef06b06de3e5a784184e7d042ab57c54"

      def install
        bin.install "todo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/caffeines/notion-todo/releases/download/v1.0.0/notion-todo_Linux_x86_64.tar.gz"
      sha256 "02c688ff177401d576037e2fef4073c12e4a5a2d0ef525402a971e84eb7a666a"
      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/caffeines/notion-todo/releases/download/v1.0.0/notion-todo_Linux_arm64.tar.gz"
      sha256 "c17bef446493d427ea4dbf93eebb951d8846a75d5e46d012eabb11fefc211d58"
      def install
        bin.install "todo"
      end
    end
  end

  test do
    system "#{bin}/todo version"
  end
end
