# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionTodo < Formula
  desc "A command-line interface for managing todo items using Notion database integration"
  homepage "https://github.com/caffeines/notion-todo"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caffeines/notion-todo/releases/download/v1.0.2/notion-todo_Darwin_x86_64.tar.gz"
      sha256 "98a1137c94f0dd78bfbde24f3b916bb7454627d22b6bbb242702608243e6cdaf"

      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caffeines/notion-todo/releases/download/v1.0.2/notion-todo_Darwin_arm64.tar.gz"
      sha256 "b95043db15724f326b2046196cb0e7784ef9b3594ebd0b024f83ecc7c77d1c8e"

      def install
        bin.install "todo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/caffeines/notion-todo/releases/download/v1.0.2/notion-todo_Linux_x86_64.tar.gz"
      sha256 "09f93e3453fdf709bd9e8eac80c7f5daf310c43be12cd59f8b537e164caf16f6"
      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/caffeines/notion-todo/releases/download/v1.0.2/notion-todo_Linux_arm64.tar.gz"
      sha256 "2ae1d376f9a834517e494680ae53457ce37e92d33008ea84d2ca333b95108350"
      def install
        bin.install "todo"
      end
    end
  end

  test do
    system "#{bin}/todo version"
  end
end
